version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "16-bullseye"
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh
    command: sleep infinity